# Generated by Django 4.1.7 on 2023-04-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PacketType",
            fields=[
                (
                    "id",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "description",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("enabled", models.BooleanField(default=False)),
            ],
        ),
    ]
