# Generated by Django 4.2.3 on 2023-07-08 12:08

from django.db import migrations
from rooms.models import Room


def create_defaults(app, editor):
    Room(name="Default Room").save()


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_defaults)]
