# Generated by Django 4.1.7 on 2023-04-23 20:58

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("transport", "0002_defaults"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="New device", max_length=200)),
                ("ident", models.CharField(default="0123456", max_length=20)),
                ("unit", models.CharField(default="1", max_length=10)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                (
                    "device_protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.protocol",
                    ),
                ),
                (
                    "packet_type",
                    models.ForeignKey(
                        default="0x03",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.packettype",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Light",
            fields=[
                (
                    "device_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.device",
                    ),
                ),
                ("state", models.BooleanField(default=False)),
                ("level", models.IntegerField(default=50)),
            ],
            options={
                "abstract": False,
            },
            bases=("api.device",),
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "device_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.device",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("api.device",),
        ),
        migrations.CreateModel(
            name="Switch",
            fields=[
                (
                    "device_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.device",
                    ),
                ),
                ("state", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            bases=("api.device",),
        ),
        migrations.AddField(
            model_name="device",
            name="room",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="api.room",
            ),
        ),
        migrations.CreateModel(
            name="Temperature",
            fields=[
                (
                    "sensor_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.sensor",
                    ),
                ),
                (
                    "temp",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("20"), max_digits=5
                    ),
                ),
                ("humidity", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("api.sensor",),
        ),
    ]
