# Generated by Django 4.1.7 on 2023-04-02 22:17

from django.db import migrations
from api.models import Room

import api.constants as const

def create_defaults(app, editor):
    Room(name="Default Room").save()
    # DeviceType(id=const.DEVICE_TYPE_SWITCH, description="Switch").save()
    # DeviceType(id=const.DEVICE_TYPE_LIGHT, description="Light").save()
    # DeviceType(id=const.DEVICE_TYPE_TEMP, description="Temperature").save()
    # DeviceType(id=const.DEVICE_TYPE_TEMP_HUM, description="Temperature + Humidity").save()
    
class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_defaults)]
