# Generated by Django 4.1.7 on 2023-04-26 22:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_defaults"),
    ]

    operations = [
        migrations.RenameField(
            model_name="light",
            old_name="level",
            new_name="brightness",
        ),
    ]
