"""
Django settings for rfx2mqtt project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

from django.utils.log import ServerFormatter

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-u5)ze9v(5b2q(_ywdhq@jm6w=beko(69g=kz&g+1p180cr==4n"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "django_bootstrap5",
    "daphne",
    "polymorphic",
    "extra_views",
    "crispy_forms",
    "crispy_bootstrap5",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_tables2",
    "django_htmx",
    "constance",
    "constance.backends.database",
    "api.apps.ApiConfig",
    "gui",
    "django_mqtt",
    "django_rfx",
    "channels",
    "drf_spectacular",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

# Crispy-forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

REST_FRAMEWORK = {
    # your other DRF settings here
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

ROOT_URLCONF = "rfx2mqtt.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "src/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

print(TEMPLATES[0]["DIRS"])

# Applications
WSGI_APPLICATION = "rfx2mqtt.wsgi.application"
ASGI_APPLICATION = "rfx2mqtt.asgi.application"

# Constanse
CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"
CONSTANCE_CONFIG = {
    "MQTT_HOST": ("127.0.0.1", ""),
    "MQTT_PORT": (1883, ""),
    "MQTT_ENABLE": (True, ""),
    "MQTT_TOPIC": ("rfx2mqtt", ""),
    "MQTT_ROOM_IN_NAME": (True, "Include room in device discovery name"),
    "RFX_ENABLE": (True, ""),
    "RFX_DEVICE": ("/dev/ttyAMC0", ""),
    "RFX_DEFAULT_PACKET_TYPE": ("0x03", ""),
    "RFX_SWITCH_ON_CREATE": (True, "Send a ON-command after adding new device"),
    "RFX_ADD_UNKNOWN": (True, "Add new devices on events"),
    "RFX_SWITCH_ON_LEVEL_SET": (True, "Set state to True on level change"),
}

# MQTT
MQTT_CONFIG = {"USE_CONSTANCE": True}
RFX_CONFIG = {"USE_CONSTANCE": True, "DEVICE": "/dev/ttyAMC1"}

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

db_path = os.getenv("RFX2MQTT_DB_PATH")
if db_path is None:
    db_path = Path("/usr/src/data")
    if not Path.is_dir(db_path):
        db_path = BASE_DIR

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": db_path / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
# STATIC_ROOT = BASE_DIR / "staticfiles"

# print(STATIC_ROOT)

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging

loglevel = os.environ.get("RFX_LOGLEVEL") if os.environ.get("RFX_LOGLEVEL") else "INFO"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": True,
    "formatters": {
        "default": {
            "()": "rfx2mqtt.log.CustomFormatter",
        }
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            # "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
            "formatter": "default",
        },
    },
    "loggers": {
        "django": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "mqtt": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "daphne": {"handlers": ["console"], "level": loglevel, "propagate": False},
        "asyncio": {"handlers": ["console"], "level": loglevel, "propagate": False},
        "api": {"handlers": ["console"], "level": loglevel, "propagate": False},
        "gui": {"handlers": ["console"], "level": loglevel, "propagate": False},
        "RFXtrx": {"handlers": ["console"], "level": loglevel, "propagate": False},
    },
}
#     "filters": {
#         "require_debug_false": {
#             "()": "django.utils.log.RequireDebugFalse",
#         },
#         "require_debug_true": {
#             "()": "django.utils.log.RequireDebugTrue",
#         },
#     },
#     "formatters": {
#         "default": {
#             "()": "rfx2mqtt.log.CustomFormatter",
#         }
#     },
#     "handlers": {
#         "console": {
#             "level": "INFO",
#             "filters": ["require_debug_true"],
#             "class": "logging.StreamHandler",
#             "formatter": "default",
#         },
#     },
#     "loggers": {
#         "django": {"handlers": ["console"], "level": "INFO", "propagate": False},
#     },
# }
