# Generated by Django 4.2.1 on 2023-07-08 18:05

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New device', max_length=200)),
                ('ident', models.CharField(default='0123456', max_length=20)),
                ('unit', models.CharField(default='1', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('state', models.BooleanField(default=False)),
                ('brightness', models.IntegerField(default=50)),
            ],
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
            ],
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('state', models.BooleanField(default=False)),
            ],
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.sensor')),
                ('temp', models.DecimalField(decimal_places=1, default=Decimal('20'), max_digits=5)),
                ('humidity', models.IntegerField(blank=True, null=True)),
            ],
            bases=('devices.sensor',),
        ),
    ]
