# Generated by Django 4.2.1 on 2023-07-10 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_rfx', '0003_defaults'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_rfx.protocol'),
        ),
        migrations.AddField(
            model_name='device',
            name='packet_type',
            field=models.ForeignKey(default='0x03', on_delete=django.db.models.deletion.CASCADE, to='django_rfx.packettype'),
        ),
    ]
