# Generated by Django 4.2.1 on 2023-08-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_device_protocol_device_packet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mqtt_discover',
            field=models.BooleanField(default=True),
        ),
    ]
